# https://jekyllrb.com/docs/configuration/options/
# global configurations

source: src
# build location must be `docs` (or root) for github pages to work
destination: docs
includes_dir: _includes
data_dir: _data
incremental: true

# folders to include/exclude from build (relative to source)
include:
  - pages


# build configurations
baseurl: "" # the subpath of your site, e.g. /blog/

defaults:
  - scope:
      path: "pages"  # limit scope to `pages` dir
    values:
      permalink: :basename
      layout: page


# other configurations

# Site settings
title: jill.codes
description: 

url: "www.jill.codes" # the base hostname & protocol for your site

author:
  fullname: Jillian Augustine, PhD.
  github: jill-augustine
  linkedin: jillianaugustine
  email: jaugur.ds@gmail.com
  # instagram: jill_codes

google_analytics: G-SB9G1QSXQ2

# Build settings
highlighter: null
markdown: kramdown

