name: jill

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUBY_VERSION=3.2.5
        - JEKYLL_VERSION=4.3.3
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ".:/jekyll/."
    # command: bundle exec jekyll serve --host 0.0.0.0
    # command: bundle exec jekyll serve --help

# To update gems according to bundle file run `docker compose run --rm jekyll bundle install`
