name: Test jekyll build in docker
on: [pull_request]
jobs:
  Docker_build_and_jekyll_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Image
        run: |
          docker compose build jekyll-build
      - name: Test jekyll build in container
        run: |
          docker compose up jekyll-build
