name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build --tag github-io:latest .
      - name: Test jekyll build in container
        run: |
          docker run --rm -it github-io bundle exec jekyll build
